name: fidelix
description: "Fidelix - Sistema de Fidelidade Digital para Pequenos Comércios"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 🗄️ Banco de Dados Local (Cadastro/Login/Pontos)
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # 📸 Scanner para o Comerciante
  mobile_scanner: ^5.1.0

  # 🏁 Geração de QR Code para o Cliente
  qr_flutter: ^4.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 🎨 Assets do Projeto
  assets:
    - assets/logofidelix.png

# Se você for testar no Android, lembre-se que o mobile_scanner 
# exige que o minSdk no arquivo android/app/build.gradle seja pelo menos 21.